var mongoose = require('mongoose');
var Schema = mongoose.Schema;



var productSchema = mongoose.Schema({
	name: String,
	description: {type: String, require: true},
	code: Schema.Types.ObjectId, //Autogenerated
	price: {type:Number,min:0},
	rating: {type:Number,min:0,max:5},
	image: String
});



module.exports = mongoose.model('Product', productSchema);